apiVersion: v2
name: postgres-db-copy-2
description: A Helm chart to copy postgres tables from one db to another db using pg_dump and pg_restore, without schema or table creation.
type: application
version: 0.1.0
appVersion: 0.1.0
maintainers:
  - name: Ambiata
    email: info@ambiata.com
    url: www.ambiata.com
